- name: Pulling the jorashid/yolo-backend:v1.0.0 image
  docker_image:
    name: jorashid/yolo-backend:v1.0.0
    source: pull

- name: Running the backend service
  docker_container:
    name: yoloBackEndService
    image: jorashid/yolo-backend:v1.0.0
    ports:
      - "5000:5000"
    detach: true
    state: started
