---
# tasks file for updatingAndInstallingDocker
- name: updating the cache
  apt: 
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker.io
    state: present

- name: Clone application code from GitHub
  git:
    repo: 'https://github.com/Vinge1718/yolo.git'  
    dest: /home/ansible/yolo
    version: master 