---
- name: Connection of Ansible with Vagrant OS
  hosts: vagrant
  become: yes
  tasks:

    - name: Install Docker
      apt:
        name:
          - docker.io
        state: present
  roles:
    - start-back-end-service
    - start-front-end-service
    # - name: Create a working directory
    #   file:
    #     path: /home/ansible/yolo
    #     state: directory  # Correct usage
    #     owner: euser
    #     mode: '0775'      # Quoted mode

    # - name: Pull jorashid/yolo-frontend and jorashid/yolo-backend images
    #   docker_image:
    #     name: jorashid/yolo-frontend:v1.0.6
    #     source: pull

    # - name: pulling jorashid/yolo-backend 
    #   docker_image:
    #     name: jorashid/yolo-backend:v1.0.0
    #     source: pull

    # - name: running backend container
    #   docker_container:
    #     name: backend-container
    #     image: jorashid/yolo-backend:v1.0.0
    #     state: started
    #     detach: true
    #     ports:
    #      - "5000:5000"

    # - name: running front end now
    #   docker_container: 
    #     name: yolo-front-end
    #     image: jorashid/yolo-frontend:v1.0.6
    #     ports:
    #     - "3000:3000"
    #     detach: true
    #     state: started
    